Update SimpleMultiSignature.sol
marc-aurele-besner/SimpleMultiSignature pull request #18
Opened 2023-03-23 14:43 UTC by Guillaume-web

function isOwner

function threshold

2023-03-23 16:14 UTC, marc-aurele-besner requested changes

2023-03-23 16:14 UTC, marc-aurele-besner commented on contracts/SimpleMultiSignature.sol
> +    emit OwnerRemoved(userAddress);
rajoute le type de l'argument que tu passes à l'événement dans la définition de l'event en haut du contract (pour les 2 que ta Pr utilise)

2023-03-23 19:51 UTC, marc-aurele-besner requested changes

2023-03-23 19:51 UTC, marc-aurele-besner commented on contracts/SimpleMultiSignature.sol
> +  event OwnerAdded(userAddress);
the type need to be defined
should be something like
```solidity
 event OwnerAdded(address owner);
```

2023-03-24 14:39 UTC, marc-aurele-besner approved these changes

2023-03-24 14:40 UTC, 0xenj approved these changes

2023-03-24 14:42 UTC, merged