Test foundry
marc-aurele-besner/SimpleMultiSignature pull request #49
Opened 2023-03-31 11:31 UTC by 0xenj

problems

2023-03-31 13:59 UTC, marc-aurele-besner requested changes

2023-03-31 13:59 UTC, marc-aurele-besner commented on contracts/test/Test-enzo.t.sol
> +    multiSignature = new SimpleMultiSignature([owner1, owner2, owner3, owner4, owner5], 3);
by doing 
```solidity
[owner1, owner2, owner3, owner4, owner5]
```
you are effectively passing a address[5] to the constructor, while the contract expect a address[]
so you need to first define in memory or in storage of the test a unfix array of address and push the owners address into it, then use that variable

2023-03-31 16:02 UTC, Guillaume-web requested changes

2023-03-31 16:02 UTC, Guillaume-web commented on .vscode/settings.json
>      "editor.tabSize": 2,
i don't want your setting.json vscode !! X)

2023-03-31 16:04 UTC, 0xenj commented on .vscode/settings.json
>      "editor.tabSize": 2,
j'ai rien changé pourtant

2023-03-31 16:10 UTC, Guillaume-web commented on .vscode/settings.json
>      "editor.tabSize": 2,
Non rien n'a changé, c'est juste qu'il y avait un saut de ligne que tu as supprimé

2023-04-02 22:16 UTC, marc-aurele-besner requested changes
your pr is out of date with the main branch, but also in the last PR that was merge, I had made a comment to be fixed, a semi colon missing on line 39 of the contract, and the PR got merged without the fix, so please upgrade your branch and fix this issue, both check need to pass before this PR get merged

2023-04-02 23:07 UTC, marc-aurele-besner approved these changes

2023-04-02 23:08 UTC, Guillaume-web approved these changes

2023-04-03 07:18 UTC, merged